### ISSUE TITLE
Non-static method cannot be called statically

### ISSUE THREAD

**Issue by ghost** [OMOSde/contao-om-imagine#15]
After updating to Contao 4.13.15 and PHP 8.1 no watermarks are on new images and I get this errormessage:
"Non-static method OMOSde\ContaoOmImagineBundle\Imagine::handleActions() cannot be called statically" at /vendor/omosde/contao-om-imagine/src/Resources/contao/classes/Imagine.php line 113"

**Comment by OMOSde** [comment]
Fixed in 9913266bdd6d1017811c98e912853a23103242f7
